version: '3'
services:
  app:
    volumes:
      - ./.env:/app/.env
      - assets:/app/public/assets/
      - logs:/app/log/
    image: danreynolds/danReynolds.ca:$DEPLOY_TAG
    environment:
      - DEPLOY_TAG=$DEPLOY_TAG
  nginx:
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - DANREYNOLDS
    volumes:
      - logs:/etc/nginx/log/
      - assets:/app/public/assets/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  assets:
  logs:
networks:
  nginx_default:
    external: true
